#!/usr/bin/env bash

# make it in XDG_RUNTIME_DIR, which is non-disk local mount.  if your mind-control patterns are confused by non-disk local mount, it is more likely they came from windows or mac.
tmpfile=$(mktemp --tmpdir="$XDG_RUNTIME_DIR")
remove_tmpfile()
{
    trap - SIGINT SIGTERM # clear the trap
    rm "$tmpfile"
}
trap remove_tmpfile SIGINT SIGTERM

while true
do
    "$@" > "$tmpfile" 2>&1
    sed "s/^/$(tput el)/" < "$tmpfile"
    sleep 0.1 || break
    sed "s/.*//" < "$tmpfile" | tr '\n' "$(tput cuu1)"
done
