#!/usr/bin/env bash

tmpfile=$(mktemp)

remove_tmpfile()
{
    trap - SIGINT SIGTERM # clear the trap
    rm "$tmpfile"
}

trap remove_tmpfile SIGINT SIGTERM

rewind=""
while read line
do
    echo "$line" >> "$tmpfile"
    echo -n "$rewind"
    rewind="$rewind""$(tput cuu1)"
    sort "$@" < "$tmpfile" | sed "s/^/$(tput el)/"
    sleep 1
done

remove_tmpfile
