#!/usr/bin/env bash

cd /sys/class/backlight/*/
brightness="$1"
max_brightness="$(<max_brightness)"
if [ "$brightness" == "" ]
then
	brightness="$max_brightness"
fi
echo "$brightness / $max_brightness"
echo -n "$brightness" | sudo tee brightness >/dev/null
